// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4xCBU8-0KwHvhhLZoF0lJFRuM7ja7Lfo',
    appId: '1:146862229887:web:0bd9c1cbb66d60d757724a',
    messagingSenderId: '146862229887',
    projectId: 'fir-assignment-69a5b',
    authDomain: 'fir-assignment-69a5b.firebaseapp.com',
    storageBucket: 'fir-assignment-69a5b.appspot.com',
    measurementId: 'G-LX0Y6MN9PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJe_4Ivx4qvuhrynZm7ycftDdLhy2CPQ',
    appId: '1:146862229887:android:6e91482ae9003a5b57724a',
    messagingSenderId: '146862229887',
    projectId: 'fir-assignment-69a5b',
    storageBucket: 'fir-assignment-69a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOag686ijdfvhCKyVXD1f7GEuzGMMzwaY',
    appId: '1:146862229887:ios:b095b01461ce29b757724a',
    messagingSenderId: '146862229887',
    projectId: 'fir-assignment-69a5b',
    storageBucket: 'fir-assignment-69a5b.appspot.com',
    iosBundleId: 'com.example.module17AssignmentFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOag686ijdfvhCKyVXD1f7GEuzGMMzwaY',
    appId: '1:146862229887:ios:bc9aa0ab9c7c629757724a',
    messagingSenderId: '146862229887',
    projectId: 'fir-assignment-69a5b',
    storageBucket: 'fir-assignment-69a5b.appspot.com',
    iosBundleId: 'com.example.module17AssignmentFirebase.RunnerTests',
  );
}
