// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjisyduinSVpoCgXZ1WY5QE52kilizMsI',
    appId: '1:1007380640032:web:3dfa0892f845b13b71e745',
    messagingSenderId: '1007380640032',
    projectId: 'flutter-firebase-a5320',
    authDomain: 'flutter-firebase-a5320.firebaseapp.com',
    storageBucket: 'flutter-firebase-a5320.appspot.com',
    measurementId: 'G-8FKCCY6DDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3Z43ul8w46ckRG4tA4FqEhEECfz-JNo',
    appId: '1:1007380640032:android:48a6b024b91233f571e745',
    messagingSenderId: '1007380640032',
    projectId: 'flutter-firebase-a5320',
    storageBucket: 'flutter-firebase-a5320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUgvIlK5_iCkenSSmnlFnZaMhEsn49cgo',
    appId: '1:1007380640032:ios:a7672c37602a4d3a71e745',
    messagingSenderId: '1007380640032',
    projectId: 'flutter-firebase-a5320',
    storageBucket: 'flutter-firebase-a5320.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAssaignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUgvIlK5_iCkenSSmnlFnZaMhEsn49cgo',
    appId: '1:1007380640032:ios:c9d57dfae021448b71e745',
    messagingSenderId: '1007380640032',
    projectId: 'flutter-firebase-a5320',
    storageBucket: 'flutter-firebase-a5320.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAssaignment.RunnerTests',
  );
}